[package]
name = "almoner_escrow"
version = "0.1.0"
edition = "2024_07"
license-file = "../LICENSE"

[dependencies]
starknet = "2.17.0"
openzeppelin = "3.0.0"
privacy = { git = "https://github.com/starkware-libs/starknet-privacy" }

[dev-dependencies]
snforge_std = "0.63.0"
assert_macros = "2.17.0"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[lib]

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"
